## This file was auto-generated by CloudCoreo CLI
	## This file was automatically generated using the CloudCoreo CLI
	##
	## This config.rb file exists to create and maintain services not related to compute.
	## for example, a VPC might be maintained using:
	##
	## coreo_aws_vpc_vpc "my-vpc" do
	##   action :sustain
	##   cidr "12.0.0.0/16"
	##   internet_gateway true
	## end
	##
coreo_aws_advisor_alert "ec2-training-check" do
  action :define
  service :ec2
  display_name "Ec2 large not encrypted snapshots"
  description "EC2 not encrypted snapshot is greater than 8GB"
  category "Inventory"
  suggested_action "None."
  level "Informational"
  id_map "object.snapshot_set.snapshot_id"
  objectives ["snapshots", "snapshots"]
  audit_objects ["snapshot_set.volume_size", "snapshot_set.encrypted"]
  operators [">", "=="]
  alert_when [8, false]
end

coreo_aws_advisor_ec2 "advise-ec2" do
  action :advise
  alerts ["ec2-training-check"]
  regions ["us-east-1"]
end